baseURL = 'https://databoss465.github.io/'
languageCode = 'en-us'
title = 'Raspy Ramblings'
theme = 'ananke'

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

  [[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 2